### ISSUE TITLE
Set a player's mumble context if they're in a live game.

### ISSUE THREAD

**Issue by alisenai** [StarGate01/AmongUs-Mumble#21] opened 2020-11-11 16:25 UTC
When joining a lobby, it may cause problems as you won't be able to talk to your friends who aren't also in that lobby.
Leaving a game often also does not trigger a "Game joined or ended" and this can also cause similar issues.

As per the [wiki](https://wiki.mumble.info/wiki/Link), the context should not be updated every frame -- will have to fix the issue with detecting game state changes.

**Comment by StarGate01** [comment] 2020-11-11 16:38
As per the current implementation, the Mumble context is initialized once the game starts, so all playersshould have the same context anyway. If I understand correctly the problem is that someone has the game not running at all, and wants to talk to the channel?

This requires a solution like the POSIX fake client, where Mumble is notified about the player but no game is running. Alternativly, we could evaluate the usage of the `manual placement plugin` to just set the context. However, I never got the plugins to work with each other, but maybe the encoding of the context `TEAM` was not correct.

> Leaving a game often also does not trigger a "Game joined or ended" and this can also cause similar issues.
Lets deal with that in #22 .

**Comment by LelouBil** [comment] 2020-11-12 19:53
If someone doesn't have the same context or any context set, they will just hear/be heard non positionally.

**Comment by StarGate01** [comment] 2020-11-16 06:16
Should be fixed by #27 . If not, feel free to reopen.

**Closed by StarGate01** 2020-11-16 06:16 UTC
Labels: discussion, enhancement
