### ISSUE TITLE
Latest version bug 

### ISSUE THREAD

**Issue by Snorfold** [StarGate01/AmongUs-Mumble#74] opened 2020-12-27 23:52 UTC
I have install the latest version but when i cut communication the voice dont stop and we cant speak by the camera :/

**Comment by StarGate01** [comment] 2020-12-28 04:34
I dont quite understand your scenario. Are you exiting the game? Mumble still continues to run independently of the game, by design.

**Comment by alisenai** [comment] 2020-12-29 01:11
Are you referring to sabotaging communications and speaking in the observation room? The first should work, but it should be noted that the latter isn't currently implemented.

**Comment by StarGate01** [comment] 2021-01-12 22:51
It has been 2 weeks, closing.

**Closed by StarGate01** 2021-01-12 22:51 UTC
Labels: more-info-needed, question
